# Generated by Django 2.2.12 on 2020-05-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('birthdate', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
