# Generated by Django 2.2.12 on 2020-05-10 20:45

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_auto_20200510_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='owners',
            field=djongo.models.fields.ArrayReferenceField(default=[], on_delete=django.db.models.deletion.CASCADE, to='facts.Person'),
            preserve_default=False,
        ),
    ]
