# Generated by Django 2.2.12 on 2020-05-10 20:53

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_farm_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='employees',
            field=djongo.models.fields.ArrayReferenceField(default=[], on_delete=django.db.models.deletion.CASCADE, related_name='farms_employed_by', to='facts.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='owners',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, related_name='farms_owned', to='facts.Person'),
        ),
    ]
