# Generated by Django 2.2.12 on 2020-05-15 17:41

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import facts.models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_auto_20200510_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faciliity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', djongo.models.fields.EmbeddedField(model_container=facts.models.MultiPolygon, null=True)),
                ('type', models.CharField(max_length=4096)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('type', models.CharField(max_length=4096)),
                ('additional_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facts.Organization')),
                ('employees', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, related_name='companies_employed_by', to='facts.Person')),
                ('owners', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, related_name='companies_owned', to='facts.Person')),
            ],
            bases=('facts.organization',),
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
    ]
